### ISSUE TITLE
[Kha] Enter or Backspace doesn't seem to work for text input

### ISSUE THREAD

**Issue by Jarrio** [Aidan63/linc_imgui#8]
![gif](https://user-images.githubusercontent.com/748557/40130038-c8f923cc-592d-11e8-8f29-3c1ba7ee7bb1.gif)

I am using the example template which has the following lines
```haxe
io.keysDown[KeyCode.Return   ] = isKeyDown[KeyCode.Return];
io.keysDown[KeyCode.Backspace] = isKeyDown[KeyCode.Backspace];
```

An odd thing I noticed when configuring the flags for component `inputText` setting the flags to:
```haxe
var flags = ImGuiInputTextFlags.EnterReturnsTrue;
flags |= ImGuiInputTextFlags.CharsUppercase;
```

Backspace would register as `Return` but Return never gets picked up

**Comment by Aidan63** [comment]
I've not been able to recreate this issue so far. I've tested on linux and the backspace works as expected and return causes inputText to return true when the flag is set. Judging from the gif it seems like you're on windows so I'll try to give it a try later today.

**Comment by Jarrio** [comment]
To confirm, I am on Windows!

Much appreciated.

**Comment by Jarrio** [comment]
I found the cause! 

It appears like the issue is actually with the version of ImGui this repo links to (I `--recursively` cloned the repo), I updated to the newest ImGui and everything seems to be working now.

**Comment by Aidan63** [comment]
Nice, just saw that ImGui 1.61 was released a few days ago so I'll try and updating the externs and hopefully that will fix it for everyone.
